### PR TITLE
Add a "Export bugs" button

### PR DESCRIPTION
**Pull request by mrbuds**
This PR add a button for serialize + compress (with LibDeflate) all errors, so you can copy/paste it on an external website.

The idea behind it is to improve a new feature on Wago
https://wago.io/news/mI5gqFujm/addon-error-reports
https://wago.io/n-c_XsV7e

This would allow (after a wago an update from @Oratory) to export a full stack of errors as a compressed string that you can copy/paste on the website for addon authors.

Pastebin is ok when the relevant error for your issue is the last error of the stack, this feature would help both addon authors get a full report of all the errors a user have.

img

img

### CODE REVIEW

**Comment by oratory** [comment]
I updated Wago to be able to use this, example here: https://wago.io/KQIO66bmH

However there is a problem with the PR. Exporting bugs for the current session generates a string for all bugs.

**Comment by mrbuds** [comment]
I have fixed it so it export only errors from current tab, and added an import button so the export feature can be used for more than just Wago.

img

**Comment by funkydude** [comment]
My main issue with this isn't the idea, it's the addition of a huge 3.5k line library for a feature I'd assume a very small amount of users would make use of.

I *think* your main goal is to copy all the errors of the current session, why can't that be done raw using special characters as separators? The user doesn't actually need to see the content that is in the export box, so it can remain small.

**Comment by mrbuds** [comment]
I'm glad you are ok with the idea.

I have remove libdeflate and export it serialized
This inflate the string a lot, so for import i had to add a trick to reduce client freeze with very big strings

I start to think the import button is a bad idea, and having a more user friendly "raw" output is a better option indeed

**Comment by mrbuds** [comment]
So i removed the import button, and export it in raw.
PR is much shorter, i have not rebase to remove previous commits so if you want it done differently previous code is still there.

**Comment by funkydude** [comment]
Looks good. If you want to put icing on the cake you can replace the static popup with a replica custom frame.

**Comment by mrbuds** [comment]
I'm gonna try but ho god i wished you didn't asked that

**Comment by funkydude** [comment]
It's not a requirement. If not, I'll get round to it at some point in the future.

**Comment by mrbuds** [comment]
Thinking more about it, i have come to the conclusion that a nicer solution that achieve the same goal is to have a button to switch to a "bulk" mode, which make the window show errors 20 per 20 instead of 1 by 1.
It would avoid freezes issues for those who never clean their sack.

**Comment by mrbuds** [comment]
I made an update where i replace the export button with a button for switching between 1 per 1 view and 20 per 20 view
You can see it in action in this clip https://www.twitch.tv/videos/443813233

I can't say i'm convinced with the button name, maybe you have a better idea.
And maybe the setting "bulkItemsPerPage" set at 20 items is a bit to high.

I think it's a better idea than previous version, what do you think ?

**Comment by funkydude** [comment]
@mrbuds Sorry, I forgot all about this. Are you not interested in this PR anymore?

I think looking into DF's built in string exporting/importing might be a bonus to this PR?

**Pull request closed without merging**
